export const INDONESIAN_TERMS = {
  // Farming Terms
  "Hen Day Production": "Hen Day Production (HDP)",
  "Feed Conversion Ratio": "Feed Conversion Ratio (FCR)",
  "Mortality": "Mortalitas",
  "Population": "Populasi",
  "Eggs": "Telur",
  "Broken Eggs": "Telur pecah",
  "Discard": "Afkir",
  "Cage": "Sangkar",
  "Floor": "Lantai",
  "Doc": "DOC",
  "Brooding": "Brooding",
  "Grower": "Grower",
  "Layer": "Layer",
  "Depopulation": "Depopulasi",
  
  // Business Terms
  "Purchase Order": "Purchase Order",
  "Sales Order": "Sales Order",
  "Invoice": "Invoice",
  "Inventory": "Inventori",
  "Stock": "Stok",
  "Transfer": "Mutasi",
  "Adjustment": "Penyesuaian",
  "Customer": "Pelanggan",
  "Supplier": "Pemasok",
  
  // UI Terms
  "Dashboard": "Dasbor",
  "Reports": "Laporan",
  "Settings": "Pengaturan",
  "Profile": "Profil",
  "Logout": "Keluar",
  "Login": "Masuk",
  "Save": "Simpan",
  "Cancel": "Batal",
  "Delete": "Hapus",
  "Edit": "Ubah",
  "View": "Lihat",
  "Search": "Cari",
  "Filter": "Filter",
  "Export": "Ekspor",
  "Print": "Cetak",
  "Download": "Unduh",
  "Add": "Tambah",
  "Update": "Perbarui",
  "Create": "Buat",
  "Submit": "Kirim",
  "Approve": "Setujui",
  "Reject": "Tolak",
  "Pending": "Menunggu",
  "Approved": "Disetujui",
  "Rejected": "Ditolak",
  "Draft": "Draft",
  "Active": "Aktif",
  "Inactive": "Tidak Aktif",
  "Yes": "Ya",
  "No": "Tidak",
  "Total": "Total",
  "Amount": "Jumlah",
  "Date": "Tanggal",
  "Time": "Waktu",
  "User": "Pengguna",
  "Action": "Aksi",
  "Module": "Modul",
  "Detail": "Detail",
  "Before": "Sebelum",
  "After": "Sesudah",
  "Change": "Perubahan",
  "History": "Riwayat",
  "Notification": "Notifikasi",
  "Alert": "Peringatan",
  "Warning": "Peringatan",
  "Error": "Kesalahan",
  "Success": "Berhasil",
  "Info": "Informasi",
  "Farm": "Peternakan",
  "Location": "Lokasi",
  "Address": "Alamat",
  "Phone": "Telepon",
  "Email": "Email",
  "Name": "Nama",
  "Code": "Kode",
  "Type": "Tipe",
  "Category": "Kategori",
  "Unit": "Satuan",
  "Price": "Harga",
  "Quantity": "Jumlah",
  "Status": "Status",
  "Notes": "Catatan",
  "Description": "Deskripsi",
  "Created": "Dibuat",
  "Updated": "Diperbarui",
  "Deleted": "Dihapus",
  "Record": "Rekam",
  "Data": "Data",
  "Information": "Informasi",
  "Configuration": "Konfigurasi",
  "System": "Sistem",
  "Security": "Keamanan",
  "Audit": "Audit",
  "Trail": "Trail",
  "Log": "Log",
  "Report": "Laporan",
  "Summary": "Ringkasan",
  "Detail": "Detail",
  "Analysis": "Analisis",
  "Performance": "Performa",
  "Efficiency": "Efisiensi",
  "Productivity": "Produktivitas",
  "Quality": "Kualitas",
  "Cost": "Biaya",
  "Expense": "Pengeluaran",
  "Revenue": "Pendapatan",
  "Profit": "Keuntungan",
  "Loss": "Kerugian",
  "Balance": "Saldo",
  "Transaction": "Transaksi",
  "Payment": "Pembayaran",
  "Receipt": "Penerimaan",
  "Due": "Jatuh Tempo",
  "Overdue": "Lewat Jatuh Tempo",
  "Paid": "Lunas",
  "Unpaid": "Belum Lunas",
  "Credit": "Kredit",
  "Debit": "Debit",
  "Account": "Akun",
  "Chart": "Bagan",
  "Journal": "Jurnal",
  "Entry": "Entri",
  "Line": "Baris",
  "Batch": "Batch",
  "Batch Code": "Kode Batch",
  "Breed": "Ras",
  "Stage": "Tahap",
  "Initial": "Awal",
  "Current": "Saat Ini",
  "Start": "Mulai",
  "End": "Akhir",
  "From": "Dari",
  "To": "Ke",
  "Between": "Antara",
  "Daily": "Harian",
  "Weekly": "Mingguan",
  "Monthly": "Bulanan",
  "Yearly": "Tahunan",
  "All": "Semua",
  "None": "Tidak Ada",
  "Select": "Pilih",
  "Choose": "Pilih",
  "Option": "Opsi",
  "Value": "Nilai",
  "Key": "Kunci",
  "ID": "ID",
  "Reference": "Referensi",
  "Related": "Terkait",
  "Parent": "Induk",
  "Child": "Anak",
  "Sibling": "Saudara",
  "Previous": "Sebelumnya",
  "Next": "Berikutnya",
  "First": "Pertama",
  "Last": "Terakhir",
  "New": "Baru",
  "Old": "Lama",
  "Recent": "Terbaru",
  "Latest": "Terakhir",
  "Earliest": "Paling Awal",
  "Sort": "Urutkan",
  "Order": "Urutan",
  "Ascending": "Naik",
  "Descending": "Turun",
  "Group": "Grup",
  "Group By": "Kelompokkan Berdasarkan",
  "Filter By": "Saring Berdasarkan",
  "Search By": "Cari Berdasarkan",
  "Show": "Tampilkan",
  "Hide": "Sembunyikan",
  "Expand": "Perluas",
  "Collapse": "Ciutkan",
  "Open": "Buka",
  "Close": "Tutup",
  "Minimize": "Minimalkan",
  "Maximize": "Maksimalkan",
  "Restore": "Pulihkan",
  "Refresh": "Segarkan",
  "Reload": "Muat Ulang",
  "Reset": "Reset",
  "Clear": "Bersihkan",
  "Clean": "Bersih",
  "Dirty": "Kotor",
  "Validate": "Validasi",
  "Verify": "Verifikasi",
  "Confirm": "Konfirmasi",
  "Accept": "Terima",
  "Decline": "Tolak",
  "Agree": "Setuju",
  "Disagree": "Tidak Setuju",
  "Continue": "Lanjutkan",
  "Stop": "Hentikan",
  "Start": "Mulai",
  "Finish": "Selesai",
  "Complete": "Selesai",
  "Incomplete": "Belum Selesai",
  "Done": "Selesai",
  "Not Done": "Belum Selesai",
  "Ready": "Siap",
  "Not Ready": "Belum Siap",
  "Available": "Tersedia",
  "Unavailable": "Tidak Tersedia",
  "Enabled": "Diaktifkan",
  "Disabled": "Dinonaktifkan",
  "On": "Nyala",
  "Off": "Mati",
  "True": "Benar",
  "False": "Salah",
  "Yes": "Ya",
  "No": "Tidak",
  "OK": "OK",
  "Cancel": "Batal",
  "Apply": "Terapkan",
  "Execute": "Eksekusi",
  "Run": "Jalankan",
  "Process": "Proses",
  "Operation": "Operasi",
  "Function": "Fungsi",
  "Feature": "Fitur",
  "Tool": "Alat",
  "Utility": "Utilitas",
  "Service": "Layanan",
  "Support": "Dukungan",
  "Help": "Bantuan",
  "Documentation": "Dokumentasi",
  "Guide": "Panduan",
  "Tutorial": "Tutorial",
  "Example": "Contoh",
  "Sample": "Sampel",
  "Template": "Template",
  "Format": "Format",
  "Style": "Gaya",
  "Theme": "Tema",
  "Color": "Warna",
  "Font": "Font",
  "Size": "Ukuran",
  "Width": "Lebar",
  "Height": "Tinggi",
  "Position": "Posisi",
  "Location": "Lokasi",
  "Coordinate": "Koordinat",
  "Map": "Peta",
  "Navigation": "Navigasi",
  "Menu": "Menu",
  "Sidebar": "Sidebar",
  "Header": "Header",
  "Footer": "Footer",
  "Content": "Konten",
  "Body": "Body",
  "Main": "Utama",
  "Primary": "Utama",
  "Secondary": "Sekunder",
  "Tertiary": "Tersier",
  "Default": "Default",
  "Custom": "Kustom",
  "Standard": "Standar",
  "Advanced": "Lanjutan",
  "Basic": "Dasar",
  "Simple": "Sederhana",
  "Complex": "Kompleks",
  "Easy": "Mudah",
  "Difficult": "Sulit",
  "Hard": "Sulit",
  "Easy": "Mudah",
  "Quick": "Cepat",
  "Slow": "Lambat",
  "Fast": "Cepat",
  "Rapid": "Cepat",
  "Instant": "Instan",
  "Immediate": "Segera",
  "Delayed": "Tertunda",
  "Scheduled": "Dijadwalkan",
  "Automatic": "Otomatis",
  "Manual": "Manual",
  "Interactive": "Interaktif",
  "Static": "Statis",
  "Dynamic": "Dinamis",
  "Responsive": "Responsif",
  "Adaptive": "Adaptif",
  "Flexible": "Fleksibel",
  "Rigid": "Kaku",
  "Loose": "Longgar",
  "Tight": "Ketat",
  "Wide": "Lebar",
  "Narrow": "Sempit",
  "Big": "Besar",
  "Small": "Kecil",
  "Large": "Besar",
  "Medium": "Sedang",
  "Tiny": "Kecil",
  "Huge": "Besar",
  "Massive": "Masif",
  "Giant": "Raksasa",
  "Mini": "Mini",
  "Micro": "Mikro",
  "Macro": "Makro",
  "Nano": "Nano",
  "Pico": "Piko",
  "Femto": "Femto",
  "Atto": "Atto",
  "Zepto": "Zepto",
  "Yocto": "Yokto"
} as const;

export const formatCurrency = (amount: number) => {
  return new Intl.NumberFormat("id-ID", {
    style: "currency",
    currency: "IDR",
    minimumFractionDigits: 0,
    maximumFractionDigits: 0
  }).format(amount);
};

export const formatDate = (date: Date | string) => {
  return new Date(date).toLocaleDateString("id-ID", {
    day: "numeric",
    month: "long",
    year: "numeric"
  });
};

export const formatDateTime = (date: Date | string) => {
  return new Date(date).toLocaleString("id-ID", {
    day: "numeric",
    month: "long",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit"
  });
};

export const formatNumber = (num: number) => {
  return new Intl.NumberFormat("id-ID").format(num);
};

export const translate = (key: string): string => {
  return INDONESIAN_TERMS[key as keyof typeof INDONESIAN_TERMS] || key;
};